# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cascadence"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Thomas Chen"]
  s.date = "2013-05-06"
  s.description = "Organizational helper for writing serializations for use with threading. The biggest use case of this would be in selenium / capybara based integration testing as this allows you to run flows in parallel."
  s.email = "foxnewsnetwork@gmail.com"
  s.executables = ["cascadence"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "bin/cascadence",
    "cascadence.gemspec",
    "fixtures/README.md",
    "fixtures/amazon/madeira_flow.rb",
    "fixtures/amazon/rio_negro_flow.rb",
    "fixtures/amazon_flow.rb",
    "fixtures/dogwood.clj",
    "fixtures/faggot_spec.rb",
    "fixtures/flow_helper.rb",
    "fixtures/lib/nothing.rb",
    "fixtures/nile/blue_nile_flow.rb",
    "fixtures/nile/white_nile/gray_nile_flow.rb",
    "fixtures/nile/white_nile_flow.rb",
    "fixtures/nile_flow.rb",
    "lib/cascadence.rb",
    "lib/cascadence/class_methods.rb",
    "lib/cascadence/commander.rb",
    "lib/cascadence/commander/flow.rb",
    "lib/cascadence/commander/generate.rb",
    "lib/cascadence/commander/version.rb",
    "lib/cascadence/config.rb",
    "lib/cascadence/confluence.rb",
    "lib/cascadence/flow.rb",
    "lib/cascadence/helper.rb",
    "lib/cascadence/runner.rb",
    "lib/cascadence/stateful.rb",
    "lib/cascadence/task.rb",
    "lib/cascadence/templates/%project_name%.rb.tt",
    "lib/cascadence/templates/%project_name%/base_flow.rb.tt",
    "lib/cascadence/templates/flow_helper.rb.tt",
    "spec/cascadence/advanced_fork_merge_spec.rb",
    "spec/cascadence/class_methods_spec.rb",
    "spec/cascadence/commander/flow_spec.rb",
    "spec/cascadence/commander/generate_spec.rb",
    "spec/cascadence/commander/version_spec.rb",
    "spec/cascadence/commander_spec.rb",
    "spec/cascadence/flow_merge_spec.rb",
    "spec/cascadence/flow_spec.rb",
    "spec/cascadence/fork_merge_spec.rb",
    "spec/cascadence/helper_spec.rb",
    "spec/cascadence/runner_spec.rb",
    "spec/cascadence/stateful_spec.rb",
    "spec/cascadence_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/foxnewsnetwork/cascadence"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.0.rc.2"
  s.summary = "Organization helper for writing flow-based integration tests using capybara and whatnot"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

