# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cascadence"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Thomas Chen"]
  s.date = "2013-02-14"
  s.description = "Organizational helper for writing serializations for use with threading. The biggest use case of this would be in selenium / capybara based integration testing as this allows you to run flows in parallel."
  s.email = "foxnewsnetwork@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "cascadence.gemspec",
    "coverage/.last_run.json",
    "coverage/.resultset.json",
    "coverage/assets/0.7.1/application.css",
    "coverage/assets/0.7.1/application.js",
    "coverage/assets/0.7.1/fancybox/blank.gif",
    "coverage/assets/0.7.1/fancybox/fancy_close.png",
    "coverage/assets/0.7.1/fancybox/fancy_loading.png",
    "coverage/assets/0.7.1/fancybox/fancy_nav_left.png",
    "coverage/assets/0.7.1/fancybox/fancy_nav_right.png",
    "coverage/assets/0.7.1/fancybox/fancy_shadow_e.png",
    "coverage/assets/0.7.1/fancybox/fancy_shadow_n.png",
    "coverage/assets/0.7.1/fancybox/fancy_shadow_ne.png",
    "coverage/assets/0.7.1/fancybox/fancy_shadow_nw.png",
    "coverage/assets/0.7.1/fancybox/fancy_shadow_s.png",
    "coverage/assets/0.7.1/fancybox/fancy_shadow_se.png",
    "coverage/assets/0.7.1/fancybox/fancy_shadow_sw.png",
    "coverage/assets/0.7.1/fancybox/fancy_shadow_w.png",
    "coverage/assets/0.7.1/fancybox/fancy_title_left.png",
    "coverage/assets/0.7.1/fancybox/fancy_title_main.png",
    "coverage/assets/0.7.1/fancybox/fancy_title_over.png",
    "coverage/assets/0.7.1/fancybox/fancy_title_right.png",
    "coverage/assets/0.7.1/fancybox/fancybox-x.png",
    "coverage/assets/0.7.1/fancybox/fancybox-y.png",
    "coverage/assets/0.7.1/fancybox/fancybox.png",
    "coverage/assets/0.7.1/favicon_green.png",
    "coverage/assets/0.7.1/favicon_red.png",
    "coverage/assets/0.7.1/favicon_yellow.png",
    "coverage/assets/0.7.1/loading.gif",
    "coverage/assets/0.7.1/magnify.png",
    "coverage/assets/0.7.1/smoothness/images/ui-bg_flat_0_aaaaaa_40x100.png",
    "coverage/assets/0.7.1/smoothness/images/ui-bg_flat_75_ffffff_40x100.png",
    "coverage/assets/0.7.1/smoothness/images/ui-bg_glass_55_fbf9ee_1x400.png",
    "coverage/assets/0.7.1/smoothness/images/ui-bg_glass_65_ffffff_1x400.png",
    "coverage/assets/0.7.1/smoothness/images/ui-bg_glass_75_dadada_1x400.png",
    "coverage/assets/0.7.1/smoothness/images/ui-bg_glass_75_e6e6e6_1x400.png",
    "coverage/assets/0.7.1/smoothness/images/ui-bg_glass_95_fef1ec_1x400.png",
    "coverage/assets/0.7.1/smoothness/images/ui-bg_highlight-soft_75_cccccc_1x100.png",
    "coverage/assets/0.7.1/smoothness/images/ui-icons_222222_256x240.png",
    "coverage/assets/0.7.1/smoothness/images/ui-icons_2e83ff_256x240.png",
    "coverage/assets/0.7.1/smoothness/images/ui-icons_454545_256x240.png",
    "coverage/assets/0.7.1/smoothness/images/ui-icons_888888_256x240.png",
    "coverage/assets/0.7.1/smoothness/images/ui-icons_cd0a0a_256x240.png",
    "coverage/index.html",
    "lib/cascadence.rb",
    "lib/cascadence/class_methods.rb",
    "lib/cascadence/flow.rb",
    "lib/cascadence/helper.rb",
    "lib/cascadence/stateful.rb",
    "spec/cascadence/class_methods_spec.rb",
    "spec/cascadence/flow_spec.rb",
    "spec/cascadence/fork_merge_spec.rb",
    "spec/cascadence/helper_spec.rb",
    "spec/cascadence/stateful_spec.rb",
    "spec/cascadence_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/foxnewsnetwork/cascadence"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Organization helper for writing flow-based integration tests using capybara and whatnot"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

